export const LABEL_MAP: Record<string, string> = {
  'ag1-look': 'Clean Clinical Trust',
  'hims-style': 'Soft Editorial Wellness',
  'ikea-minimal': 'Minimal Modern Set',
  'beauty-skin': 'Beauty Editorial Soft Skin',
  'studio-pro': 'Soft Studio Light',
  'beauty-style': 'Beauty Editorial Look',
  'ag1-style': 'Clean Clinical Trust',
  'sunrise-ritual': 'Sunrise Wellness Counter',
  'Sunrise Ritual Counter': 'Sunrise Wellness Counter',
  'crown-ritual': 'Crown Wellness Vanity',
  'Crown Ritual Vanity': 'Crown Wellness Vanity',
  'dawn_ritual': 'Dawn Wellness Scene',
  'Dawn Ritual Compression': 'Dawn Wellness Scene',
};
