export type ProductStudioStep3Values = {
  sceneIntent?: 'environment' | 'ecommerce';
  aspectRatio: string;
  sidePlacement?: string;
  ecommerceSidePlacementFlag?: boolean;
  ecommerceBackgroundMode?: 'white' | 'gradient';
  ecommerceBackgroundColor?: string;
  ecommerceGradientStart?: string;
  ecommerceGradientEnd?: string;
  ecommerceGradientAngle?: string;
  productType?: string;
  productTypeCustom?: string;
  productCameraSystem?: string;
  productCameraAngle?: string;
  productCameraDistance?: string;
  productCameraRotation?: number;
  productFramingGuide?: string;
  productCreativityLevel?: string;
  productCreativeTheme?: string;
  productPaletteSource?: string;
  productPropDensity?: string;
  productPropsSelected?: string[];
  environment?: string;
  customEnvironment?: string;
  lightingStyle?: string;
  ugcRealMode?: boolean;
  noPerson?: boolean;
  selfieMode?: string;
  productStructure?: string;
};
